### PR TITLE
Token authorization.

### PR DESCRIPTION
**Pull request by kb000**

### CODE REVIEW

**Comment by kb000** [comment]
I haven't smoke tested this yet.  I'll complete the PR once I do.

**Comment by kb000** [comment]
Can one of the admins verify this patch?

**Comment by kb000** [comment]
Jenkins, test this please.

**Comment by kb000** [comment]
Jenkins, test this please.

**Comment by kb000** [comment]
buddybuild now

**Comment by kb000** [comment]
buddybuild now

**Comment by kb000** [comment]
buddybuild now.

**Review by Dairai — APPROVED** [review]
Looks good to me. I trust it builds fine on your machine. I will take a deeper dive for my understanding when i download it

**Pull request merged**
